import type { Metadata } from "next";
import "../globals.css";
import SideBar from "@/components/SideBar/SideBar";

export const metadata: Metadata = {
    title: "Next.Js Cours",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex h-screen">
            <SideBar />
            <div className="flex-1 flex flex-col">
                <main className="flex-1 p-6">{children}</main>
            </div>
        </div>
    );
}
