import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
    title: "Next.Js Cours",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex h-screen">
            {/* Sidebar */}
            <aside className="w-64 bg-blue-600 text-white p-6 flex flex-col">
                <h2 className="text-2xl font-bold mb-6">Navigation</h2>
                <ul className="space-y-4">
                    <li>
                        <a href="/" className="block py-2 px-4 rounded hover:bg-blue-700">
                            Accueil
                        </a>
                    </li>
                    <li>
                        <a href="/about" className="block py-2 px-4 rounded hover:bg-blue-700">
                            À propos
                        </a>
                    </li>
                    <li>
                        <a href="/contact" className="block py-2 px-4 rounded hover:bg-blue-700">
                            Contact
                        </a>
                    </li>
                    <li>
                        <a href="/project" className="block py-2 px-4 rounded hover:bg-blue-700">
                            Projets
                        </a>
                    </li>
                </ul>
                <footer className="mt-auto text-sm text-center">
                    © {new Date().getFullYear()} by GAUDIN Luidgi
                </footer>
            </aside>

            {/* Main Content */}
            <div className="flex-1 flex flex-col">
                <main className="flex-1 p-6">{children}</main>
            </div>
        </div>
    );
}
