import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/header";

export const metadata: Metadata = {
  title: "Next.Js Cours",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="fr">
      <body className="bg-gray-50 text-gray-800">
      <Header />
      <main>{children}</main>
      <footer className="bg-blue-600 text-white p-4">
        <div className="container mx-auto text-center">
          © {new Date().getFullYear()} by GAUDIN Luidgi
        </div>
      </footer>
      </body>
      </html>
  );
}
